### ISSUE TITLE
Error on running "To sticker Sets"

### ISSUE THREAD

**Issue by SergeyTitarenko** [vognik/maltego-telegram#1]
<img width="422" alt="issue" src="https://github.com/user-attachments/assets/d7dacfe3-d653-486f-8524-a652567be59c">

**Comment by vognik** [comment]
Make sure that Python is installed and added to the environment variables. Alternatively, specify the path manually through the Transform Manager in Maltego.
![screenshot](https://github.com/user-attachments/assets/5c275682-8ab5-4b3a-a275-10e3b3eecf26)
